"""
scripts/extract_version.py

从 pyproject.toml 提取版本号并生成 _version.py 文件
用于 GitHub Actions workflow 中，统一处理版本号提取逻辑。
"""

import os
import re
from datetime import datetime, timezone
import tomllib


def get_git_info() -> dict[str, str]:
    """获取 Git 信息（仅在 CI 环境中从环境变量获取）"""
    info = {
        "commit_hash": "",
        "commit_hash_short": "",
        "branch": "",
        "tag": "",
    }

    # GitHub Actions 环境变量
    if "GITHUB_SHA" in os.environ:
        info["commit_hash"] = os.environ["GITHUB_SHA"]
        info["commit_hash_short"] = info["commit_hash"][:7]

    if "GITHUB_REF_NAME" in os.environ:
        ref_name = os.environ["GITHUB_REF_NAME"]
        if os.environ.get("GITHUB_REF_TYPE") == "tag":
            info["tag"] = ref_name
        else:
            info["branch"] = ref_name

    return info


def main():
    # 获取构建时间（UTC）
    build_time = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")

    # 获取 Git 信息
    git_info = get_git_info()

    # 读取 pyproject.toml
    with open("pyproject.toml", "rb") as f:
        data = tomllib.load(f)
        version = data["project"]["version"]

    print(f"Detected version: {version}")
    print(f"Commit: {git_info['commit_hash_short']}")
    print(f"Branch: {git_info['branch']}")
    print(f"Tag: {git_info['tag']}")
    print(f"Build time: {build_time}")

    # 生成 _version.py 供 Python 代码引用
    with open("src/ba_modding_toolkit/_version.py", "w", encoding="utf-8") as f:
        f.write(f'"""METADATA - generated by extract_version.py"""\n')
        f.write(f'__version__ = "{version}"\n')
        f.write(f'__commit_hash__ = "{git_info["commit_hash"]}"\n')
        f.write(f'__commit_hash_short__ = "{git_info["commit_hash_short"]}"\n')
        f.write(f'__branch__ = "{git_info["branch"]}"\n')
        f.write(f'__tag__ = "{git_info["tag"]}"\n')
        f.write(f'__build_time__ = "{build_time}"\n')

    # Nuitka 的 file-version 必须是纯数字格式 (如 1.2.3.4)
    # 提取开头的数字段（支持最多四段，遇到非数字/点就停）
    match = re.match(r'[vV]?(\d+)\.(\d+)\.(\d+)(?:\.(\d+))?', version)
    if match:
        major, minor, patch, fourth = match.groups()
        major = major or '0'
        minor = minor or '0'
        patch = patch or '0'

        # 如果第四段已经存在（原版本号有四位数字），直接使用
        if fourth is not None:
            file_version = f"{major}.{minor}.{patch}.{fourth}"
        else:
            # 没有第四段，判断是否为预发布版
            if re.search(r'(alpha|beta|rc|dev|a|b|c)', version, re.I):
                file_version = f"{major}.{minor}.{patch}.8888"
            else:
                file_version = f"{major}.{minor}.{patch}.0"
    else:
        file_version = "0.0.0.0"
    print(f"File version for Nuitka: {file_version}")

    # 将版本号设置到 GitHub Action 的输出变量
    if 'GITHUB_OUTPUT' in os.environ:
        with open(os.environ['GITHUB_OUTPUT'], 'a') as fh:
            print(f"version={version}", file=fh)
            print(f"file_version={file_version}", file=fh)
    else:
        # 本地运行时输出到 stdout
        print(f"::set-output name=version::{version}")
        print(f"::set-output name=file_version::{file_version}")


if __name__ == "__main__":
    main()